# Example Application.yml file
#
# all provided fields need to be filed to make app work

default_email: "something@something.com"
default_email_pwd: "something"

endpoint_email: "something@something.com"

smtp_address: "something.com"
smtp_domain: "something.info"
smtp_port: "someport"

googleKey: "somekey"
googleServerKey: "someserverkey"

SECRET_KEY_BASE: "railssecretkey"